version: "3.11"

services:
  redis:
    image: redis:7-alpine
    container_name: crypto-change-bot-redis
    restart: always
    env_file: .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis-data:${REDIS_DATA}
    networks:
      - common

  postgres:
    image: postgres:16-alpine
    container_name: crypto-change-bot-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    networks:
      - common

  parser:
    image: parser
    container_name: crypto-change-bot-parser
    restart: always
    build:
      context: parser
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file: .env
    networks:
      - common

  scanner:
    image: scanner
    container_name: crypto-change-bot-scanner
    restart: always
    build:
      context: scanner
      dockerfile: Dockerfile
    depends_on:
      - redis
      - parser
    env_file: .env
    networks:
      - common

  bot:
    build: ./bot
    container_name: crypto-change-bot-bot
    restart: always
    env_file: .env
    depends_on:
      - redis
      - postgres
    networks:
      - common

volumes:
  redis-data:

networks:
  common:
    driver: bridge